<?php
// JEO - Replace this class with something autogenerated
class Light_MVC_Config {
   public static function BASE_DIR() { return '/Users/jorcutt/pfl/web'; }
   public static function BASE_URL() { return 'http://jorcutt-laptop'; }
   public static function SITE_TITLE() { return 'Project: Feles Lectus'; }
   public static function SESSION_NAME() { return 'pfl_session'; }
   public static function CSS_FILES() { return array (  0 => 'common.css',); }
}
